---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: cert-manager
  labels:
    kubeaddons.mesosphere.io/name: cert-manager
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.13.1-1"
    appversion.kubeaddons.mesosphere.io/cert-manager: "0.13.1"
    docs.kubeaddons.mesosphere.io/cert-manager: "https://cert-manager.io/docs/"
    values.chart.helm.kubeaddons.mesosphere.io/cert-manager: "https://raw.githubusercontent.com/mesosphere/charts/sebbrandt87/cert-manager-update/staging/cert-manager-setup/values.yaml"
spec:
  namespace: cert-manager
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: cert-manager-setup
    repo: https://mesosphere.github.io/charts/staging
    version: 0.2.0
    values: |
      ---
      clusterissuer:
        name: kubernetes-ca
        spec:
          ca:
            secretName: kubernetes-intermediate-ca
