---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: istio
  labels:
    kubeaddons.mesosphere.io/name: istio
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.4.3-3"
    appversion.kubeaddons.mesosphere.io/istio: "1.4.3"
    appversion.kubeaddons.mesosphere.io/kiali: "1.4.3"
    appversion.kubeaddons.mesosphere.io/jaeger: "1.4.3"
    stage.kubeaddons.mesosphere.io/kiali: Preview
    stage.kubeaddons.mesosphere.io/jaeger: Preview
    endpoint.kubeaddons.mesosphere.io/kiali: "/ops/portal/kiali"
    endpoint.kubeaddons.mesosphere.io/jaeger: "/ops/portal/jaeger"
    docs.kubeaddons.mesosphere.io/istio: "https://istio.io/docs/"
    docs.kubeaddons.mesosphere.io/kiali: "https://istio.io/docs/tasks/telemetry/kiali/"
    docs.kubeaddons.mesosphere.io/jaeger: "https://istio.io/docs/tasks/telemetry/distributed-tracing/jaeger/"
    values.chart.helm.kubeaddons.mesosphere.io/istio: "https://raw.githubusercontent.com/mesosphere/charts/63bbc17eda76f2136f6ab4f6d6eef7e764e5f0a5/staging/istio/values.yaml"
spec:
  namespace: istio-system
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: cert-manager
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: false
    - name: azure
      enabled: false
    - name: docker
      enabled: false
    - name: none
      enabled: false
  chartReference:
    chart: istio
    repo: https://mesosphere.github.io/charts/staging
    version: 1.4.3
    values: |
      kiali:
        enabled: true
        contextPath: /ops/portal/kiali
        ingress:
          enabled: true
          kubernetes.io/ingress.class: traefik
          hosts:
            - ""
        dashboard:
          auth:
            strategy: anonymous
        prometheusAddr: http://prometheus-kubeaddons-prom-prometheus.kubeaddons:9090

      tracing:
        enabled: true
        contextPath: /ops/portal/jaeger
        ingress:
          enabled: true
          kubernetes.io/ingress.class: traefik
          hosts:
            - ""

      grafana:
        enabled: true

      prometheus:
        serviceName: prometheus-kubeaddons-prom-prometheus.kubeaddons

      istiocoredns:
        enabled: true

      security:
        selfSigned: false
        caCert: /etc/cacerts/tls.crt
        caKey: /etc/cacerts/tls.key
        rootCert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        certChain: /etc/cacerts/tls.crt
        enableNamespacesByDefault: false

      global:
        podDNSSearchNamespaces:
        - global
        - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"
        defaultPodDisruptionBudget:
          enabled: false

        mtls:
          enabled: true

        multiCluster:
          enabled: true

        controlPlaneSecurityEnabled: true

      gateways:
        enabled: true
        cluster-local-gateway:
          enabled: false
          labels:
            app: cluster-local-gateway
            istio: cluster-local-gateway
          replicaCount: 1
          autoscaleMin: 1
          autoscaleMax: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
          cpu:
            targetAverageUtilization: 60
          loadBalancerIP: ""
          loadBalancerSourceRanges: {}
          externalIPs: []
          serviceAnnotations: {}
          podAnnotations: {}
          type: ClusterIP
          ports:
          - port: 80
            targetPort: 80
            name: http2
          - port: 443
            name: https
          - port: 31400
            name: tcp
          - port: 15011
            targetPort: 15011
            name: tcp-pilot-grpc-tls
          - port: 8060
            targetPort: 8060
            name: tcp-citadel-grpc-tls
          - port: 15029
            targetPort: 15029
            name: http2-kiali
          - port: 15030
            targetPort: 15030
            name: http2-prometheus
          - port: 15031
            targetPort: 15031
            name: http2-grafana
          - port: 15032
            targetPort: 15032
            name: http2-tracing
          secretVolumes:
          - name: clusterlocalgateway-certs
            secretName: istio-clusterlocalgateway-certs
            mountPath: /etc/istio/clusterlocalgateway-certs
          - name: clusterlocalgateway-ca-certs
            secretName: istio-clusterlocalgateway-ca-certs
            mountPath: /etc/istio/clusterlocalgateway-ca-certs
